Create Splash Screen
chjch/jaxtwin pull request #2
Opened 2024-08-23 00:38 UTC by pinnockf

- Creates a splash screen that will hide itself when the view has finishe loading

2024-08-23 03:05 UTC, chjch requested changes
Franklin, I tested it on my local. Works very well! Thanks! Just a small change is that I'd like Jax to appear first and wait a timeout of 1000 for Twin to be appear. Could you please make that change?

2024-08-23 03:05 UTC, chjch commented on pyproject.toml
I'm not really sure about this file and its usage, as well as requirements-dev.lock and requirements.lock. can we include only things related to the splash in this PR for now. And deal with building files later?

2024-08-23 16:25 UTC, pinnockf commented on .python-version
> +3.10.0
I am using a package manager called Rye for my python environment. This file makes it easy to control which version of python is used by the app. I was using to try to see if the app would work with a lower version of python like Reggie suggested. I will add all of the files used by Rye to the .gitignore

2024-08-23 17:05 UTC, pinnockf commented on package.json
> +    "webpack-cli": "5.1.4"
Locked the package versions and removed `css-loader`

2024-08-23 18:06 UTC, pinnockf commented on jtflask/jtdash/layout.py
> +                <h1 class='animate__animated animate__fadeInUp'>Twin</h1>
The animation library has a utility class that we can use to delay any animation. I've updated the logo to use it

2024-08-23 18:13 UTC, pinnockf commented on package.json
> +    "css-loader": "^6.10.0",
I was trying to see if I can use the webpack-dev-server package to serve the files so that I wouldnt have to build every single time that I wanted to make a simple change. The dev server would re-render the page automatically every time a change is made. But it didnt want to spend too much time getting it to work. `css-loader` is a dependency for `webpack-dev-server`. 

I've removed it from the package.json

2024-08-23 18:14 UTC, pinnockf commented on pyproject.toml
I've added the files to the gitignore

2024-08-30 19:40 UTC, chjch commented
The feature has been incorporated into the main branch at this [commit](https://github.com/chjch/jaxtwin/tree/caa2f35f9c22a774bad66ee065c8b678ee7dbc59). Close PR.

2024-08-30 19:40 UTC, closed without merging